In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

In [ ]:
# upload file 
import pandas as pd
df3 = pd.read_excel('/content/drive/MyDrive/MC/Assessments/A2 & A3/scraped_data/Master files/df3.xlsx', header=0)

In [ ]:
df3.head()

Unnamed: 0                                            comment hashtag  \
0           0  Another amazing video! So wonderful to see all...  Hazara   
1           1  Beautiful people, love from Iran to my lovely ...  Hazara   
2           2                             Love my nation Hazara   Hazara   
3           3                                 Be healthy friends  Hazara   
4           4                             Greetings, dear people  Hazara   

  target basis  prejudicial  offensive  ironic  stereotype  
0    NaN   NaN            0          0       0           0  
1    NaN   NaN            0          0       0           0  
2    NaN   NaN            0          0       0           0  
3    NaN   NaN            0          0       0           0  
4    NaN   NaN            0          0       0           0

In [ ]:
df3.drop(['Unnamed: 0'], axis=1, inplace=True)

**df_na** is the non-annotated set. It has 1984 rows. 

**df3** is the annotated set. It has 549 rows.

## Word embeddings

Input = **df3**

In [ ]:
import io
import os
import re
import shutil
import string
from numpy import array
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import TextVectorization

In [ ]:
# create list of comments
docs = df3['comment'].str.split(',').apply(lambda x: ', '.join([i.strip() for i in x])).tolist()

In [ ]:
docs

In [ ]:
# define class labels
labels = df3['stereotype'].to_numpy()
print(labels)

[0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1
 1 1 1 0 0 1 1 0 0 1 0 1 0 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1 1 1 1 1 1 1 0 1 0 1
 1 0 1 1 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 1 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 0 1 1 1 1 0 0 1 0 1
 1 0 0 0 1 1 1 1 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 0 1 1 0 1 1 1 0 0 0 1 1 0 1 0 1 0 0 0 0
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0
 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 1 0 1 1 0 0 0 1 1 0 0 1 1 0 1 0 1 1 1 1 1 1
 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1
 1 1 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 1 1 1
 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0
 1 0 0 1 0 0 1 0 0 1 1 0 

In [ ]:
unique_words = set(" ".join(docs).split())
vocab_size = len(unique_words)

In [ ]:
vocab_size

3287

In [ ]:
# integer encode the documents
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[3010, 1902, 968, 258, 199, 143, 2888, 2840, 399, 1726, 660, 2741, 2842, 1534, 2517, 2741, 200, 806], [155, 946, 1132, 2495, 1819, 143, 3280, 119, 2934, 2741, 133], [1132, 3280, 2531, 1534], [2622, 2638, 715], [1952, 856, 946], [2110, 204, 2942, 503, 1534, 588, 310, 80, 2741, 72, 2586, 1712, 2382, 994, 588, 310, 2951, 80, 1338, 786, 262, 515, 1807, 2749, 2453, 1534, 946, 107, 1805, 2145, 1114, 503, 80, 1801, 282, 2741, 1505, 140, 192, 80, 1508, 1338, 244, 204, 3089, 2741, 1508, 37, 2622, 140, 653, 311, 2020], [349, 310, 3200, 2222, 2445, 3280, 856, 241, 349, 310, 3156, 311, 542], [155, 180, 192, 1910, 2741, 1726, 961, 2, 200, 846, 503, 351, 275, 1454, 961, 2272, 666], [2841, 1252, 467, 503, 3104, 311, 244], [2942, 143, 2622, 1534, 181], [3280, 856, 2110, 445, 2942, 311, 1901, 2741, 3041, 3156, 311, 349, 3280, 133, 2110, 445, 2222, 1534, 3123, 349, 310, 582, 1334, 3200, 1355, 214, 2359, 582, 846, 2110, 445, 2942, 143, 2622, 2222, 1534], [1057, 1791, 1804, 311, 244, 2110, 1401, 561, 148

In [ ]:
# pad documents to a max length of 20 words
# 19 is the av length of comments
max_length = 20
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[3010 1902  968 ...  806    0    0]
 [ 155  946 1132 ...    0    0    0]
 [1132 3280 2531 ...    0    0    0]
 ...
 [ 502 3089 1565 ... 2222 1564 2531]
 [ 856  366  668 ...    0    0    0]
 [1488 3200 2460 ... 2222 1406  438]]


In [ ]:
# Create a custom standardization function to strip HTML break tags '<br />'.
def custom_standardization(input_data):
  lowercase = tf.strings.lower(input_data)
  stripped_html = tf.strings.regex_replace(lowercase, '<br />', ' ')
  return tf.strings.regex_replace(stripped_html,
                                  '[%s]' % re.escape(string.punctuation), '')

### Create vector to word mapping

In [ ]:
# Vocabulary size and number of words in a sequence.
sequence_length = 20

# Use the text vectorization layer to normalize, split, and map strings to
# integers. Note that the layer uses the custom standardization defined above.
# Set maximum_sequence length as all samples are not of the same length.
vectorize_layer = TextVectorization(
    standardize=custom_standardization,
    max_tokens=vocab_size,
    output_mode='int',
    output_sequence_length=sequence_length)

# Make a text-only dataset (no labels) and call adapt to build the vocabulary.
text_ds = docs #train_ds.map(lambda x, y: x)
vectorize_layer.adapt(text_ds)
print(vectorize_layer.get_vocabulary())

['', '[UNK]', 'the', 'and', 'to', 'of', 'in', 'i', 'are', 'is', 'they', 'you', 'a', 'for', 'hazara', 'people', 'this', 'but', 'it', 'that', 'not', 'all', 'from', 'on', 'be', 'afghanistan', 'their', 'have', 'more', 'hazaras', 'them', 'what', 'who', 'so', 'taliban', 'we', 'as', 'by', 'about', 'am', 'with', 'will', 'do', 'my', 'proud', 'if', 'were', 'us', 'like', 'why', 'or', 'no', 'your', 'read', 'was', 'world', 'there', 'dont', 'can', 'women', 'these', 'afghan', 'when', 'im', 'at', 'one', 'only', 'country', 'because', 'would', 'live', 'just', 'up', 'out', 'our', 'should', 'now', 'against', 'other', 'mashallah', 'look', 'years', 'see', 'iran', 'has', 'good', 'being', 'an', 'news', 'many', 'very', 'than', 'pakistan', 'video', 'muslims', 'most', 'its', 'how', 'did', 'back', 'time', 'same', 'pakistani', 'never', 'need', 'mongolia', 'love', 'islam', 'india', 'great', 'chinese', 'been', 'any', 'where', 'u', 'support', 'rights', 'religion', 'peaceful', 'me', 'had', 'go', 'genocide', 'fight', '

### Define the model 

Tensorflow is the Google ML framework used to build the Neural Network.  'Sigmoid' is used as the activation function to give probability which gives a result from 0 to 1 and is used for this binary classification task.  

In [ ]:
# define the model via add() method
# vocab size 3287
model = Sequential()
model.add(Embedding(vocab_size, 20, name="embedding", input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid')) # output later

In [ ]:
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# summarize the model
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 20)            65740     
                                                                 
 flatten (Flatten)           (None, 400)               0         
                                                                 
 dense (Dense)               (None, 1)                 401       
                                                                 
Total params: 66,141
Trainable params: 66,141
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
# fit the model
model.fit(padded_docs, labels, epochs=70, verbose=1)

Epoch 1/70
18/18 [==============================] - 1s 6ms/step - loss: 0.6917 - accuracy: 0.5428
Epoch 2/70
18/18 [==============================] - 0s 3ms/step - loss: 0.6702 - accuracy: 0.7195
Epoch 3/70
18/18 [==============================] - 0s 3ms/step - loss: 0.6485 - accuracy: 0.7887
Epoch 4/70
18/18 [==============================] - 0s 3ms/step - loss: 0.6235 - accuracy: 0.8106
Epoch 5/70
18/18 [==============================] - 0s 3ms/step - loss: 0.5923 - accuracy: 0.8270
Epoch 6/70
18/18 [==============================] - 0s 3ms/step - loss: 0.5563 - accuracy: 0.8707
Epoch 7/70
18/18 [==============================] - 0s 3ms/step - loss: 0.5151 - accuracy: 0.8889
Epoch 8/70
18/18 [==============================] - 0s 3ms/step - loss: 0.4696 - accuracy: 0.9107
Epoch 9/70
18/18 [==============================] - 0s 3ms/step - loss: 0.4227 - accuracy: 0.9271
Epoch 10/70
18/18 [==============================] - 0s 3ms/step - loss: 0.3759 - accuracy: 0.9472
Epoch 11/70
18/18 [

In [ ]:
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 100.000000


In [ ]:
weights = model.get_layer('embedding').get_weights()[0]
vocab = vectorize_layer.get_vocabulary()

In [ ]:
print(vectorize_layer.get_vocabulary())

['', '[UNK]', 'the', 'and', 'to', 'of', 'in', 'i', 'are', 'is', 'they', 'you', 'a', 'for', 'hazara', 'people', 'this', 'but', 'it', 'that', 'not', 'all', 'from', 'on', 'be', 'afghanistan', 'their', 'have', 'more', 'hazaras', 'them', 'what', 'who', 'so', 'taliban', 'we', 'as', 'by', 'about', 'am', 'with', 'will', 'do', 'my', 'proud', 'if', 'were', 'us', 'like', 'why', 'or', 'no', 'your', 'read', 'was', 'world', 'there', 'dont', 'can', 'women', 'these', 'afghan', 'when', 'im', 'at', 'one', 'only', 'country', 'because', 'would', 'live', 'just', 'up', 'out', 'our', 'should', 'now', 'against', 'other', 'mashallah', 'look', 'years', 'see', 'iran', 'has', 'good', 'being', 'an', 'news', 'many', 'very', 'than', 'pakistan', 'video', 'muslims', 'most', 'its', 'how', 'did', 'back', 'time', 'same', 'pakistani', 'never', 'need', 'mongolia', 'love', 'islam', 'india', 'great', 'chinese', 'been', 'any', 'where', 'u', 'support', 'rights', 'religion', 'peaceful', 'me', 'had', 'go', 'genocide', 'fight', '

In [ ]:
out_v = io.open('yt_vectors.tsv', 'w', encoding='utf-8')
out_m = io.open('yt_metadata.tsv', 'w', encoding='utf-8')

for index, word in enumerate(vocab):
  if index == 0:
    continue  # skip 0, it's padding.
  vec = weights[index]
  print(word)
  print(vec)

  out_v.write('\t'.join([str(x) for x in vec]) + "\n")
  out_m.write(word + "\n")
out_v.close()
out_m.close()


Streaming output truncated to the last 5000 lines.
 -0.20840862 -0.09928045]
public
[-0.02946067 -0.0193193   0.03087137  0.04668064  0.02054856  0.03815005
 -0.02189673 -0.00028511  0.00055132 -0.03572917  0.03954556 -0.00344666
 -0.03586654 -0.00307383 -0.01568128  0.02670674 -0.02213492  0.02159787
 -0.04243612 -0.01890974]
provenance
[ 0.0263576  -0.00232329 -0.04392315  0.04280483 -0.00812961 -0.02685672
  0.04262349 -0.02183936 -0.0419517   0.00911335 -0.04703983 -0.04881855
  0.02627839  0.04697596  0.00505023  0.0235386   0.01878366  0.00241827
  0.01810243  0.02249329]
proved
[-0.04005464 -0.03593521 -0.00334921 -0.00725398  0.04435191 -0.04249952
  0.00014701 -0.02595728  0.04896352  0.00654406 -0.0393431  -0.04721619
 -0.00172843  0.00642874 -0.00667354 -0.02823376 -0.0438164  -0.02553896
 -0.03109099  0.02022565]
prove
[-0.14643736 -0.04219827 -0.05237521 -0.0647777  -0.01697705 -0.01732838
  0.0010301   0.21506958 -0.18327217  0.11299031 -0.09658528 -0.16747083
  0.1305263

In [ ]:
try:
  from google.colab import files
  files.download('yt_vectors.tsv') # vectors
  files.download('yt_metadata.tsv') # list of words
except Exception:
  pass

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>